import pandas as pd
import os
from datetime import datetime

def update_job_search_data(new_records_path, final_csv_path='job_applications_final.csv'):
    """
    Merges new scraped records into the final CSV, handling duplicates and updating statuses.
    """
    if not os.path.exists(new_records_path):
        print(f"Error: {new_records_path} not found.")
        return

    # Load existing and new data
    df_new = pd.read_csv(new_records_path)
    
    if os.path.exists(final_csv_path):
        df_final = pd.read_csv(final_csv_path)
        
        # Merge logic: 
        # 1. Append new records
        # 2. Sort by date (descending)
        # 3. Drop duplicates based on company and job_title, keeping the latest one
        # (This allows updates to response_status if a response came in for an existing app)
        df_combined = pd.concat([df_final, df_new], ignore_index=True)
        
        # Ensure date format for proper sorting and consistent storage
        for col in ['application_date', 'response_date']:
            df_combined[col] = pd.to_datetime(df_combined[col], errors='coerce', format='mixed').dt.strftime('%Y-%m-%d')
        
        df_combined = df_combined.sort_values(by=['application_date', 'response_date'], ascending=False, na_position='last')
        
        # Standardize job_title to handle duplicates with missing titles
        df_combined['job_title'] = df_combined['job_title'].fillna('N/A').str.strip()
        df_combined['company'] = df_combined['company'].fillna('Unknown').str.strip()

        # Drop duplicates but prioritize informative statuses
        status_priority = {
            'Rejected': 4,
            'Interview': 4,
            'Technical Test': 3,
            'Questionnaire': 3,
            'Update Received': 2,
            'In Progress': 2,
            'Received': 1,
            'No Response': 0
        }
        df_combined['status_rank'] = df_combined['response_status'].apply(
            lambda x: status_priority.get(x, 1) if pd.notnull(x) else 0
        )
        
        # Sort by status_rank descending and application_date descending
        df_combined = df_combined.sort_values(
            by=['company', 'job_title', 'status_rank', 'application_date'], 
            ascending=[True, True, False, False]
        )
        df_combined = df_combined.drop_duplicates(subset=['company', 'job_title'], keep='first')
        df_combined = df_combined.drop(columns=['status_rank'])
    else:
        df_combined = df_new

    # Save and clean up
    df_combined.to_csv(final_csv_path, index=False)
    print(f"Successfully updated {final_csv_path}. Total records: {len(df_combined)}")

if __name__ == "__main__":
    # This expects a 'batch_new.csv' generated by the agent during the skill execution
    update_job_search_data('batch_new.csv')
